name: Build Docker image and push to GHCR

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: cfpb/actions/docker-build-push@5b3ff0ebe0ac88a69752a6e0fff1b73a2f6ebcf9
        with:
          image-name: consumer-credit-trends-data
          token: ${{ secrets.GITHUB_TOKEN }}
